version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-realworld
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: realworld
      MYSQL_USER: realworld_user
      MYSQL_PASSWORD: realworld_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: